public class ViaCepJson {
    
    @AuraEnabled public String cep;
    @AuraEnabled public String logradouro;
    @AuraEnabled public String complemento;
    @AuraEnabled public String bairro;
    @AuraEnabled public String localidade;
    @AuraEnabled public String uf;
    @AuraEnabled public String unidade;
    @AuraEnabled public String ibge;
    @AuraEnabled public String gia;
        
    public ViaCepJson() {

    }
}